import { useMemo, useState } from "react";
import { Background, Controls, MiniMap, ReactFlow, type Edge, type Node } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { Brain, Download, Maximize, RefreshCw, X } from "lucide-react";
import { createMindMapCacheKey, type MindMapDepth, type MindMapNode, type MindMapScope } from "../lib/mindMap";
import { readMindMapCache, writeMindMapCache } from "../lib/mindMapCache";
import { requestMindMap } from "../lib/mindMapRequest";
export function MindMapDrawer({ open, onClose, pages, currentPage, onNavigateToPage }: { open:boolean; onClose:()=>void; pages:Record<number,string>; currentPage:number; onNavigateToPage:(page:number)=>void }) {
 const [scope,setScope]=useState<MindMapScope>("whole_lecture"), [depth,setDepth]=useState<MindMapDepth>("normal"), [map,setMap]=useState<MindMapNode|null>(null), [loading,setLoading]=useState(false), [error,setError]=useState<string|null>(null);
 const content=useMemo(()=>Object.entries(pages).map(([page,text])=>({page:Number(page),text})),[pages]);
 const key=createMindMapCacheKey({documentId:"lesson-01",scope,depth,pages:content.map(x=>x.page),content:content.map(x=>x.text).join("")});
 const graph=useMemo(()=>{ if(!map)return {nodes:[],edges:[]}; const nodes:Node[]=[]; const edges:Edge[]=[]; let i=0; const visit=(n:MindMapNode,d=0,p?:string)=>{nodes.push({id:n.id,position:{x:d*260,y:i++*115},data:{label:<button className="text-left" onClick={()=>n.pageReferences[0]&&onNavigateToPage(n.pageReferences[0])}><b>{n.title}</b><p className="mt-1 text-xs text-slate-500">{n.summary}</p></button>},style:{width:220,padding:12,borderRadius:12,border:"1px solid #bfdbfe",background:"white"}}); if(p)edges.push({id:`${p}-${n.id}`,source:p,target:n.id,type:"smoothstep",animated:true}); n.children.forEach(c=>visit(c,d+1,n.id));};visit(map);return{nodes,edges};},[map,onNavigateToPage]);
 const generate=async()=>{setError(null);setLoading(true);try{const cached=readMindMapCache(key);if(cached){setMap(cached);return;} if(!content.length)throw new Error("Đang phân tích PDF... vui lòng thử lại sau khi các trang được tải."); const result=await requestMindMap({documentId:"lesson-01",content:scope==="current_page"?content.filter(x=>x.page===currentPage):content,scope,depth});writeMindMapCache(key,result);setMap(result);}catch(e){setError(e instanceof Error?e.message:"Không thể tạo sơ đồ tư duy.");}finally{setLoading(false);}};
 if(!open)return null; return <div className="fixed inset-y-0 right-0 z-[85] flex w-full max-w-3xl flex-col border-l border-slate-200 bg-white shadow-2xl dark:border-slate-800 dark:bg-slate-950"><header className="flex items-center justify-between border-b p-4"><h2 className="flex items-center gap-2 font-bold"><Brain className="text-blue-600"/>Sơ đồ tư duy</h2><button onClick={onClose}><X/></button></header><div className="flex flex-wrap gap-2 border-b p-3 text-xs"><label>Phạm vi <select value={scope} onChange={e=>setScope(e.target.value as MindMapScope)}><option value="whole_lecture">Toàn bộ bài giảng</option><option value="current_page">Trang hiện tại</option><option value="selected_pages">Trang đã chọn</option></select></label><label>Độ sâu <select value={depth} onChange={e=>setDepth(e.target.value as MindMapDepth)}><option value="overview">Tổng quan</option><option value="normal">Chuẩn</option><option value="detailed">Chi tiết</option></select></label></div><main className="relative min-h-0 flex-1">{loading?<div className="grid h-full place-items-center text-sm text-slate-500">AI đang xây dựng sơ đồ...<div className="mt-3 h-20 w-40 animate-pulse rounded-xl bg-slate-100"/></div>:map?<ReactFlow nodes={graph.nodes} edges={graph.edges} fitView><MiniMap/><Controls/><Background gap={18}/></ReactFlow>:<div className="grid h-full place-items-center text-slate-500">Chưa tạo</div>}{error&&<p className="absolute bottom-4 left-4 rounded bg-rose-50 p-2 text-xs text-rose-700">{error}</p>}</main><footer className="flex gap-2 border-t p-3"><button onClick={generate} className="rounded bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><RefreshCw className="mr-1 inline w-3"/>Tạo lại</button><button onClick={()=>window.print()} className="rounded border px-3 py-2 text-xs"><Maximize className="mr-1 inline w-3"/>Fit View</button><button onClick={()=>{const blob=new Blob([JSON.stringify(map,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mind-map.json";a.click();}} className="rounded border px-3 py-2 text-xs"><Download className="mr-1 inline w-3"/>Tải JSON</button></footer></div>;
}
